name: jikan_api
version: 1.6.0
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  built_value: ^8.1.2
  built_collection: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.1
  built_value_generator: ^8.1.2
  pedantic: ^1.11.1
  test: ^1.17.11
