name: jikan_api
description: Dart wrapper for the Jikan API, an unofficial MyAnimeList API.
version: 2.2.1
homepage: https://github.com/javoeria/jikan-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.2
  built_value: ^8.8.1
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1
  lints: ^3.0.0
  test: ^1.24.9

topics:
  - anime
  - manga
  - api
  - http
